### ISSUE TITLE
Impossible to add a card

### ISSUE THREAD

**Issue by ticketapp** [ignivalancy/mangopay-client-react#3]
Hello, I cannot add a card and get this error message: 

```
Object {
  "ResultCode": "105204",
  "ResultMessage": "CVVFORMATERROR",
}

```
Here is what I do (the pre-registration works well):
```
const cardRegData = { currencyCode: "EUR" };
  MangoPayClient.getCardRegisterationData(cardRegData).then(result => {
    const preRegData = {
      Id: result.Id,
      cardRegistrationURL: result.CardRegistrationURL,
      preregistrationData: result.PreregistrationData,
      accessKey: result.AccessKey
    };
    const cardData = {
      cardNumber: "4706750000000009",
      cardType: "CB_VISA_MASTERCARD",
      cardCvx: "494",
      cardExpirationDate: "1221"
    };
    MangoPayClient.registerCard(preRegData, cardData).then(result => {
      console.log(result);
    });
  });

```

I have absolutely no idea of what else coud I do so any help would be very very appreciated, thanks in advance

**Comment by ticketapp** [comment]
It seems that the Validator.js file misses this snipped:
```
      if (cardType === "CB_VISA_MASTERCARD" && cvv.length === 3) {
        return true;
      }
```

But then I still get this error:
` "ResultCode": "001596",
  "ResultMessage": "An HTTP request was blocked by the User's computer (probably due to an antivirus)",
`

**Comment by ticketapp** [comment]
I would like to add a PR with this snippet of code:
```
           if (cardType === "CB_VISA_MASTERCARD" && cvv.length === 3) {
                return true;
            }
```
in the cvvValidator function but I don't have the permissions to push a new branch :(

**Comment by lancygoyal** [comment]
This is already same, please have a look.

https://github.com/ignivalancy/mangopay-client-react/blob/master/lib/Validator.js#L34

cvvValidator(cvv, cardType) {

        if (cardType === "MAESTRO" || cardType === "BCMC") {
            return true;
        }
        cvv = cvv.trim();
        cardType = cardType.trim();

        // CVV is 3 to 4 digits for AMEX cards and 3 digits for all other cards
        if (this.validateNumericOnly(cvv) === true) {
            if (cardType === "AMEX" && (cvv.length === 3 || cvv.length === 4)) {
                return true;
            }
            if ( (cardType === "CBVISAMASTERCARD" || cardType === "CB_VISA_MASTERCARD") && cvv.length === 3) {
                return true;
            }
        }

        // Invalid format
        return {
            "ResultCode": "105204",
            "ResultMessage": "CVVFORMATERROR"
        };

    }

**Comment by ticketapp** [comment]
Indeed. But it's not version I got with yarn add mangopay-client-react

**Comment by lancygoyal** [comment]
code and version updated on npm, Please check now.

And this repo this no longer accessible. code in moved to [mangopay-client-react](https://github.com/lancygoyal/mangopay-client-react).
